In [160]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

%matplotlib inline

## Load Data

In [ ]:
raw_path = './data/raw/abundance_stoolsubset.txt'
raw_df = pd.read_csv(raw_path, sep='\t', dtype=str)

In [162]:
# inspect df shape and structure
print(raw_df.shape)
raw_df.head(5)

(2338, 1990)

,dataset_name,Candela_Africa,Candela_Africa.1,Candela_Africa.2,Candela_Africa.3,Candela_Africa.4,Candela_Africa.5,Candela_Africa.6,Candela_Africa.7,Candela_Africa.8,...,Zeller_fecal_colorectal_cancer.124,Zeller_fecal_colorectal_cancer.125,Zeller_fecal_colorectal_cancer.126,Zeller_fecal_colorectal_cancer.127,Zeller_fecal_colorectal_cancer.128,Zeller_fecal_colorectal_cancer.129,Zeller_fecal_colorectal_cancer.130,Zeller_fecal_colorectal_cancer.131,Zeller_fecal_colorectal_cancer.132,Zeller_fecal_colorectal_cancer.133
0,sampleID,H10,H11,H12,H13,H14,H15,H16,H17,H18,...,CCIS91228662ST-4-0,CCIS93040568ST-20-0,CCIS94417875ST-3-0,CCIS94496512ST-4-0,CCIS95097901ST-4-0,CCIS95409808ST-4-0,CCIS96387239ST-4-0,CCIS98482370ST-3-0,CCIS98512455ST-4-0,CCIS98832363ST-4-0
1,subjectID,h10,h11,h12,h13,h14,h15,h16,h17,h18,...,fr-275,fr-682,fr-110,fr-229,fr-696,fr-152,fr-626,fr-052,fr-459,fr-552
2,bodysite,stool,stool,stool,stool,stool,stool,stool,stool,stool,...,stool,stool,stool,stool,stool,stool,stool,stool,stool,stool
3,disease,n,n,n,n,n,n,n,n,n,...,cancer,n,n,small_adenoma,n,n,small_adenoma,n,cancer,cancer
4,age,40,29,8,34,30,16,21,23,17,...,63,65,59,64,52,63,66,53,63,55

## Clean Header

In [163]:
# transpose df to have rows as dataset_name
df = raw_df.T

# and set the first row as the new headers
df.columns = df.iloc[0]
df = df[1:]

# inspect updated df
df.head(5)

dataset_name,sampleID,subjectID,bodysite,disease,age,gender,country,sequencing_technology,pubmedid,camp,...,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Enterococcaceae|g__Enterococcus|s__Enterococcus_gilvus|t__Enterococcus_gilvus_unclassified,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis|t__GCF_000415925,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum|s__Desulfotomaculum_ruminis,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum|s__Desulfotomaculum_ruminis|t__GCF_000215085,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Faecalibacterium|s__Faecalibacterium_prausnitzii|t__GCF_000209855,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Selenomonadales|f__Veillonellaceae|g__Megasphaera|s__Megasphaera_sp_BV3C16_1,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Selenomonadales|f__Veillonellaceae|g__Megasphaera|s__Megasphaera_sp_BV3C16_1|t__GCF_000478965
Candela_Africa,H10,h10,stool,n,40,female,tanzania,Illumina,25981789,dedauko,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.1,H11,h11,stool,n,29,female,tanzania,Illumina,25981789,dedauko,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.2,H12,h12,stool,n,8,female,tanzania,Illumina,25981789,dedauko,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.3,H13,h13,stool,n,34,male,tanzania,Illumina,25981789,dedauko,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.4,H14,h14,stool,n,30,male,tanzania,Illumina,25981789,dedauko,...,0,0,0,0,0,0,0,0,0,0

## Split Metadata vs Taxa

In [164]:
# metadata columns to keep
metadata_cols = ['sampleID', 'subjectID', 'bodysite', 'disease', 'age', 'gender', 'country', 'bmi_class']
metadata_df = df[metadata_cols].copy()
metadata_df

dataset_name,sampleID,subjectID,bodysite,disease,age,gender,country,bmi_class
Candela_Africa,H10,h10,stool,n,40,female,tanzania,nd
Candela_Africa.1,H11,h11,stool,n,29,female,tanzania,nd
Candela_Africa.2,H12,h12,stool,n,8,female,tanzania,nd
Candela_Africa.3,H13,h13,stool,n,34,male,tanzania,nd
Candela_Africa.4,H14,h14,stool,n,30,male,tanzania,nd
...,...,...,...,...,...,...,...,...
Zeller_fecal_colorectal_cancer.129,CCIS95409808ST-4-0,fr-152,stool,n,63,female,france,nd
Zeller_fecal_colorectal_cancer.130,CCIS96387239ST-4-0,fr-626,stool,small_adenoma,66,male,france,nd
Zeller_fecal_colorectal_cancer.131,CCIS98482370ST-3-0,fr-052,stool,n,53,female,france,nd
Zeller_fecal_colorectal_cancer.132,CCIS98512455ST-4-0,fr-459,stool,cancer,63,male,france,nd
Zeller_fecal_colorectal_cancer.133,CCIS98832363ST-4-0,fr-552,stool,cancer,55,female,france,nd

In [165]:
# taxa columns
taxa_cols = [col for col in df.columns if col.startswith('k_')]
taxa_df = df[taxa_cols].copy()
taxa_df

dataset_name,k__Archaea,k__Archaea|p__Euryarchaeota,k__Archaea|p__Euryarchaeota|c__Methanobacteria,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii|t__Methanobrevibacter_smithii_unclassified,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_unclassified,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanosphaera,...,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Enterococcaceae|g__Enterococcus|s__Enterococcus_gilvus|t__Enterococcus_gilvus_unclassified,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis|t__GCF_000415925,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum|s__Desulfotomaculum_ruminis,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum|s__Desulfotomaculum_ruminis|t__GCF_000215085,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Faecalibacterium|s__Faecalibacterium_prausnitzii|t__GCF_000209855,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Selenomonadales|f__Veillonellaceae|g__Megasphaera|s__Megasphaera_sp_BV3C16_1,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Selenomonadales|f__Veillonellaceae|g__Megasphaera|s__Megasphaera_sp_BV3C16_1|t__GCF_000478965
Candela_Africa,0.24169,0.24169,0.24169,0.24169,0.24169,0.24169,0.24169,0.24169,0,0,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.1,0.50621,0.50621,0.50621,0.50621,0.50621,0.50621,0.50621,0.50621,0,0,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.2,0.30522,0.30522,0.30522,0.30522,0.30522,0.30522,0.30522,0.30522,0,0,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.3,0.40133,0.40133,0.40133,0.40133,0.40133,0.35994,0.35994,0.35994,0,0.04139,...,0,0,0,0,0,0,0,0,0,0
Candela_Africa.4,0.17479,0.17479,0.17479,0.17479,0.17479,0.16331,0.1528,0.1528,0.01051,0.01148,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zeller_fecal_colorectal_cancer.129,6.59835,6.59835,6.59835,6.59835,6.59835,6.59835,6.59835,6.59835,0,0,...,0,0,0,0,0,0,0,0,0,0
Zeller_fecal_colorectal_cancer.130,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zeller_fecal_colorectal_cancer.131,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zeller_fecal_colorectal_cancer.132,0.17495,0.17495,0.17495,0.17495,0.17495,0.17495,0.1689,0.1689,0.00605,0,...,0,0,0,0,0,0,0,0,0,0
Zeller_fecal_colorectal_cancer.133,0.08997,0.08997,0.08997,0.08997,0.08997,0.08997,0.00135,0.00135,0.08861,0,...,0,0,0,0,0,0,0,0,0,0

## Data Cleaning

In [166]:
taxa_df.describe(include='all')

dataset_name,k__Archaea,k__Archaea|p__Euryarchaeota,k__Archaea|p__Euryarchaeota|c__Methanobacteria,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii|t__Methanobrevibacter_smithii_unclassified,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_unclassified,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanosphaera,...,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Enterococcaceae|g__Enterococcus|s__Enterococcus_gilvus|t__Enterococcus_gilvus_unclassified,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis,k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_otakiensis|t__GCF_000415925,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum|s__Desulfotomaculum_ruminis,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae|g__Desulfotomaculum|s__Desulfotomaculum_ruminis|t__GCF_000215085,k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Faecalibacterium|s__Faecalibacterium_prausnitzii|t__GCF_000209855,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Selenomonadales|f__Veillonellaceae|g__Megasphaera|s__Megasphaera_sp_BV3C16_1,k__Bacteria|p__Firmicutes|c__Negativicutes|o__Selenomonadales|f__Veillonellaceae|g__Megasphaera|s__Megasphaera_sp_BV3C16_1|t__GCF_000478965
count,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,...,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989
unique,711,711,703,703,703,689,668,668,303,133,...,6,2,2,2,2,2,2,2,2,2
top,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
freq,1256,1256,1264,1264,1264,1277,1306,1306,1665,1850,...,1984,1988,1988,1988,1988,1988,1988,1988,1988,1988

In [167]:
metadata_df.describe(include='all')

dataset_name,sampleID,subjectID,bodysite,disease,age,gender,country,bmi_class
count,1989,1989,1989,1989,1989,1989,1989,1989
unique,1746,1562,1,18,202,6,19,6
top,MH0048,-,stool,n,nd,male,china,nd
freq,3,20,1989,944,527,783,576,1931

In [168]:
# drop columns 'bodysite' (all are stool samples) and 'bmi_class' (97% missing this info)
metadata_df = metadata_df.drop(columns=['bodysite', 'bmi_class'])

In [169]:
# rename 'n' in the 'disease' column as 'normal'
metadata_df['disease'] = metadata_df['disease'].replace('n', 'normal')

In [170]:
metadata_df.describe()

dataset_name sampleID subjectID disease   age gender country
count            1989      1989    1989  1989   1989    1989
unique           1746      1562      18   202      6      19
top            MH0048         -  normal    nd   male   china
freq                3        20     944   527    783     576

In [171]:
# replace all missing data as NaN
metadata_df.replace(['-', 'nd'], np.nan, inplace=True)

In [172]:
metadata_df.describe()

dataset_name sampleID subjectID disease   age gender country
count            1989      1989    1982  1462   1513    1945
unique           1746      1562      17   201      4      18
top            MH0048         -  normal    49   male   china
freq                3        20     944    68    783     576

#### There still are some missing values in the 'subjectID' column, why?

In [173]:
metadata_df['subjectID'].value_counts().idxmax()

' -'

In [174]:
# strip all whitespaces 
metadata_df['subjectID'] = metadata_df['subjectID'].str.strip()

In [175]:
# replace all missing data as NaN
metadata_df.replace(['-', 'nd', 'na'], np.nan, inplace=True)

In [176]:
metadata_df.describe()

dataset_name sampleID  subjectID disease   age gender country
count            1989       1969    1982  1459   1512    1945
unique           1746       1561      17   200      3      18
top            MH0048  159753524  normal    49   male   china
freq                3          5     944    68    783     576

In [177]:
# how many missing values in each category?
print(metadata_df.isna().sum())

dataset_name
sampleID       0
subjectID     20
disease        7
age          530
gender       477
country       44
dtype: int64

In [178]:
# remove entries with missing subject ID or disease label (required for classification)
metadata_df = metadata_df[metadata_df['subjectID'].notna() & metadata_df['disease'].notna()]

In [179]:
print(metadata_df.isna().sum())

dataset_name
sampleID       0
subjectID      0
disease        0
age          528
gender       476
country       44
dtype: int64

In [180]:
metadata_df.describe()

dataset_name sampleID  subjectID disease   age gender country
count            1962       1962    1962  1434   1486    1918
unique           1719       1554      16   197      2      17
top            MH0047  159753524  normal    49   male   china
freq                3          5     944    68    780     576

## Save Cleaned DataFrames

In [188]:
import os

# ensure the 'processed' directory exists
processed_dir = './data/processed/'
if not os.path.exists(processed_dir):
    os.makedirs(processed_dir)

# save the cleaned DataFrames 
taxa_output_path = os.path.join(processed_dir, 'taxa_cleaned.csv')
metadata_output_path = os.path.join(processed_dir, 'metadata_cleaned.csv')

taxa_df.to_csv(taxa_output_path, index=False)
metadata_df.to_csv(metadata_output_path, index=False)

print(f"Cleaned taxa data saved to {taxa_output_path}")
print(f"Cleaned metadata data saved to {metadata_output_path}")

Cleaned taxa data saved to ./data/processed/taxa_cleaned.csv
Cleaned metadata data saved to ./data/processed/metadata_cleaned.csv